from logic.game import Game
def main():
    game = Game()
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    game.new_keypress("j")
    print(game.get_gamestate())
if __name__ == "__main__":
    main()